### ISSUE TITLE
repl?

### ISSUE THREAD

**Issue by wboeke** [henriquegogo/kamby#4]
What do you do with a lisp without printed output in the repl (if run in a terminal)?
Or did I miss something?

**Comment by henriquegogo** [comment]
Just use "puts (expression)"

**Comment by wboeke** [comment]
Thanks!
I tried 'print', 'display' and 'write', but I should have read line 69 in main.c.

**Comment by mikewarot** [comment]
I assumed the program was broken because it doesn't act like the online example.

If you type 
1 + 2
into the online example, you get the output 
3

why doesn't the program do the same when run from the command line?  It's very confusing/inconsistent

python, for example properly returns 3 when given the same input
